[build]
  command = "netlify build"
  publish = "public"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript"

[[headers]]
for = "/manifest.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"

[[headers]]
for = "/*.css"
[headers.values]
Content-Type = "text/css"

[[plugins]]
  package = "netlify-plugin-gatsby"

[[edge_functions]]
  function = "ssr"
  path = "/lantern/*"